---
title: "Contenidos"
classoption: twocolumn
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- 

:::: {style="display: flex;"}

::: {}

:::

::: {}

:::

::::



otro forma de columnas
https://holtzy.github.io/Pimp-my-rmd/#text_formating

<div class = "row">
  
<div class = "col-md-4">
<br><br> 

[bootstrap framework](https://getbootstrap.com/docs/4.0/layout/grid/) under the hood. It is Row is divided in 12 subunits of same width. 

</div>
  
<div class = "col-md-4">
<br><br>Here, I use 3 subunits of size 4 (4x3=12). 

</div>
  
<div class = "col-md-4">
``{r, message=FALSE, echo=FALSE}
ggplot( mtcars, aes(x=mpg)) + geom_histogram(fill="skyblue", alpha=0.5) + theme_minimal()
``
</div>
</div>

-->

<!-- **********************************************************************  -->
<div class = "row">

<div class = "col-md-4">
<br><br> 

## Semana 1  {.columns-2}
(13-Sept. a 19-Sept.)

  * [Introducción](./docs/Tema00.html)
  * [Tema 01 - Introducción a R y a RStudio](./docs/Tema01.html)

<br>

</div>
  
<div class = "col-md-4">
<br><br>

## Semana 2
(20-Sept. a 24-Sept.)


  * [Tema 01 - Ejercicio](./docs/Tema01_ejerc.html)
    - Plantilla de Archivo .R a rellenar [aquí](https://raw.githubusercontent.com/albarran/BigDataEcon2021/main/Tema01_ejerc.R)
    - Entregar [aquí](https://docs.google.com/forms/d/e/1FAIpQLSfNcz7-CZ4fZOFL4KJzgVNGpcrVMSTjzqsRX8e5HW08hb3B1g/viewform) 
    - Fecha:  lun. 27-Sept. 18:00h


<br>

</div>
  
<div class = "col-md-4">
<br><br>

## Semana 3
(27-Sept. a 1-Oct.)


  * [Tema 02 - Extendiendo R](./docs/Tema02.html)

<br>

</div>
</div>


<!-- **********************************************************************  -->
<div class = "row">

<div class = "col-md-4">
<br><br> 

## Semana 4
(4-Oct. a 8-Oct.)

  * [Tema 03 - Visualización de datos](./docs/Tema03.html)
  
  * [Tema 03 - Ejercicio](./docs/Tema03_ejerc.html)
    - Entregar [aquí](https://docs.google.com/forms/d/e/1FAIpQLSccdbd-7YhwJ2jSEEYbu9tWg4cjkw2run1wBioaiza5B-f6kQ/viewform) 
    - Fecha:  mie. 13-Oct. 18:00h

<br>

</div>
  
<div class = "col-md-4">
<br><br>

## Semana 5
(11-Oct. a 15-Oct.)

  * [Tema 04 - Introducción a R Markdown](./docs/Tema04.html)
  
  * [Tema 04 - Ejercicio](./docs/Tema04_ejerc.html)
    - Entregar [aquí](https://docs.google.com/forms/d/e/1FAIpQLSfiztzC-uNclcnwywhCLGwWAoOLG6GC6510hBote3ufooN8GA/viewform) 

    (NOTA: este ejercicio NO es evaluable para Evaluación NO Continua)

<br>

</div>
  
<div class = "col-md-4">
<br><br>

## Semana 6
(18-Oct. a 23-Oct.)

 * [Tema 05 - Manipulación de Datos](./docs/Tema05.html)
 * [Tema 05 - Ejercicio](./docs/Tema05_Ejerc.html)

<br>

</div>
</div>


<!-- ********************************************************************** -->
<div class = "row">

<div class = "col-md-4">
<br><br> 

## Semana 7
(25-Oct. a 29-Oct.)

 * [Tema 06 - Manipulación de Datos Relacionales](./docs/Tema06.html)
 
 
<br>

</div>

<div class = "col-md-4">
<br><br> 


## Semana 8
(2-Nov. a 5-Nov.)

 * [Tema 06 - Ejercicio](./docs/Tema06_Ejerc.html)

</div>

<div class = "col-md-4">
<br><br> 



## Semana 9
(9-Nov. a 13-Nov.)

 * [Tema 07 - Datos Ordenados](./docs/Tema07.html)
 * [Tema 07 - Ejercicio](./docs/Tema07_Ejerc.html)
    - Entregar [aquí](https://docs.google.com/forms/d/e/1FAIpQLSfKMmZTCo0Yd-AY47p5BWM-yEwI3EvtbvxgB-183jAyylHAKQ/viewform)
    - Fecha:  dom. 14-Nov. 22:00h

  * [Tema 08 - Funciones  y Bucles](./docs/Tema08.html)
  * [Tema 08 - Ejercicio](./docs/Tema08_Ejerc.html)  
</div>
</div>

<!-- ********************************************************************** -->
<div class = "row">

<div class = "col-md-4">
<br><br> 

## Semana 10
(15-Nov. a 19-Nov.)

  * [Tema 09 - Análisis Exploratorio de Datos](./docs/Tema09.html)
  * [Tema 09 - Ejercicio](./docs/Tema09_Ejerc.html)
    + Este ejercicio NO hay que entregarlo, solo está disponible a efectos ilustrativos.
  * [Tema 10 - Fundamentos Estadísticos](./docs/Tema10.html)
  * [Tema 10 - Ejercicio](./docs/Tema10_Ejerc.html)

  
</div>
</div>

<!--
## Semana 11
(23-Nov. a 27-Nov.)

  * [Tema 08 - Aprendizaje estadístico](Tema08sl.html)
  
  * [Tema 09 - Regresión Lineal](Tema09sl.html)

::: 


::: {}

## Semana 12
(30-Nov. a 04-Dic.)

  * [Tema 10 - Regresión Logística](Tema10sl.html)
  * [Tema 11 - Selección y regularización](Tema11sl.html)

  * [Practica 05A - Proceso de Modelización"](Pract05A.html) 


::: 

::::


<!-- ********************************************************************** 
<div class = "row">

<div class = "col-md-4">
<br><br> 

## Semana 13
(07-Dic. a 11-Dic.)

  * [Practica 05B - "Tidymodels"](Pract05B.html) 

::: 


::: {}

## Semana 14
(14-Dic. a 18-Dic.)

  * [Tema 12 - kNN](Tema12sl.html)
  * [Tema 13 - Métodos de árboles](Tema13sl.html)

  * [Tema 14 - Apendizaje no supervisado](Tema14sl.html)



::: 


::: {}

## Semana 15
(21-Dic. a 23-Dic.)

  * [Ejemplo de Trabajo](Proyect01.html)


::: 

::::

-->