---
title: "Técnicas para 'Big Data' en Economía"
subtitle: "Universidad de Alicante, Otoño 2021-2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Profesor: [Pedro Albarrán](https://sites.google.com/site/pedroalbarran)

* Despacho 19, Segundo (último) piso, Edificio 31
[(Facultad de Ciencias Económicas y Empresariales)](https://www.google.es/maps/@38.3835237,-0.5130815,17z)

* e-mail: [albarran@ua.es](mailto:albarran@ua.es)


* Tutorias:

    + Lunes de 11 a 13h

    + Jueves de 16 a 18h

    + Viernes de 11 a 13h

(solicitada previamente con al menos 24 horas de antelación, por UACloud o email)

* También podéis usar UACloud


# Requisitos

-   Para el seguimiento habitual de las clases y para la realización de ejercicios, prácticas, etc. es **imprescindible** un ordenador con R y RStudio instalados.


- Tres Componentes: 

    1. Programación
    
    2. Obtención y Procesamiento de Datos
    
    3. Modelos de Aprendizaje Estadístico

-   Más detalles a lo largo del curso y en 
<!-- para **Economía** -->
[la ficha de la asignatura](https://cvnet.cpd.ua.es/Guia-Docente/GuiaDocente/Index?wcodasi=35047&scaca=2021-22)

<!--
-   Más detalles a lo largo del curso y en la ficha de la asignatura, [para **Economía** ](https://cvnet.cpd.ua.es/Guia-Docente/GuiaDocente/Index?wcodasi=35047&scaca=2020-21) o [para **ADE**](https://cvnet.cpd.ua.es/Guia-Docente/GuiaDocente/Index?wcodasi=22036&scaca=2020-21)
-->

# Evaluación 

## Continua:

  * Ejercicios teórico-prácticos durante el periodo de clases (30%)

      - preguntas y pequeñas prácticas en clase
    
      - ejercicios (más largos) a entregar

  * Trabajo empírico final (45%)

  * Examen final (25%)

  * Requisito: asistir al menos a un 80% de las clases.


## No Continua:

  * Trabajo empírico final (50%)

  * Examen final (50%)



<!--
## UAB, 16-18 June, 2021

### [Pedro Albarrán](https://sites.google.com/site/pedroalbarran) (Universidad de Alicante)


# Syllabus

* [pdf](Syllabus_CausalInference_UAB.pdf)

 
# Unit 1

   * [Slides](Unit1.html)
   
   * [NSW data](https://github.com/albarran/TopicsCausalInference/raw/main/data/nsw.dta)
   
   * [Stata code](https://github.com/albarran/TopicsCausalInference/blob/main/code/01nsw.do)
   
   * [R code](https://github.com/albarran/TopicsCausalInference/blob/main/code/01nswl.R)
   
   * Python:
      * [Jupyter Notebook](https://github.com/albarran/TopicsCausalInference/blob/main/code/01nsw.ipynb)
      * [Jupyter Notebook in Google Colab](https://colab.research.google.com/drive/1RvsDZt3AoOhjKwNchhzD1WUERL4oGyft?usp=sharing)
   
# Unit 2

   * [Slides](Unit2.html)
   
   * [Stata code](https://github.com/albarran/TopicsCausalInference/blob/main/code/collider_discrimination.do)
   
   * [R code](https://github.com/albarran/TopicsCausalInference/blob/main/code/collider_discrimination.R)
   
   * [Jupyter code](https://github.com/albarran/TopicsCausalInference/blob/main/code/collider_discrimination.py)

# Unit 3

   * [Slides](Unit3.html)

   * [CPS data](https://github.com/albarran/TopicsCausalInference/raw/main/data/cps.dta)
   
   * [Stata code](https://github.com/albarran/TopicsCausalInference/blob/main/code/unit3.do)
   
   * [R code](https://github.com/albarran/TopicsCausalInference/blob/main/code/unit3.R)
   

# Unit 4

   * [Slides](Unit4.html)

# Unit 5

   * [Slides](Unit5.html)
   
   
   * [Growth Example](growth.html)

   * [Causal Trees](CT.html)
   
-->
